name: docker-project
# to write services like redis or anything related to our app

# services: #everything we write under this tag is what dockerizes our entire django app

services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    image: docker-image
    container_name: docker-container
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    # depends_on:
    #   - db

#   db:
#     image: postgres:17
#     container_name: postgres-db
#     restart: always
#     environment:
#       POSTGRES_USER: my_user
#       POSTGRES_PASSWORD: my_password
#       POSTGRES_DB: my_database
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     ports:
#       - "5432:5432"
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready -U my_user -d my_database"]
#       interval: 10s
#       timeout: 5s
#       retries: 5

# volumes:
#   postgres_data: